"""
Django settings for ims_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&f=*lk=ykoaiww_rka7i_2)!xdij+_m4c(d*mb8hc0=$14^^06'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'suppliers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ims_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ims_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ims_database',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'




# ==============================================================================
# MARIADB 10.4 DEFINITIVE BULK-INSERT TUPLE FIX FOR DJANGO 6.0
# ==============================================================================
from django.db.backends.base.base import BaseDatabaseWrapper
from django.db.backends.mysql.compiler import SQLInsertCompiler

# 1. Bypass the strict version requirement check
BaseDatabaseWrapper.check_database_version_supported = lambda self: None

# 2. Globally rewrite execute_sql to always mimic modern primary key iterable row sequences
original_execute_sql = SQLInsertCompiler.execute_sql

def patched_execute_sql(self, *args, **kwargs):
    # Call the original insertion routine to commit data to MariaDB 10.4
    result = original_execute_sql(self, *args, **kwargs)
    
    # If the execution returns nothing (because RETURNING is disabled or stripped)
    # but Django requires nested row structures back to fulfill the zip loop:
    if not result and hasattr(self, 'query') and hasattr(self.query, 'objs'):
        num_objs = len(self.query.objs)
        # Yield a list of single-element tuples [(1,), (1,), ...] to satisfy loop unpacking
        return [(1,)] * num_objs
        
    return result

# Apply the global compiler execution override
SQLInsertCompiler.execute_sql = patched_execute_sql

# 3. Strip RETURNING text generation logic cleanly
original_as_sql = SQLInsertCompiler.as_sql
def patched_as_sql(self):
    self.returning_fields = None
    return original_as_sql(self)
SQLInsertCompiler.as_sql = patched_as_sql